### ISSUE TITLE
Customizable reports: draw graph from data output

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#1030]
[<img src="https://devserver3.ustadmobile.com/jenkins/job/dev-customizable-reports-draw-graph-from-data-output/badge/icon">](https://devserver3.ustadmobile.com/jenkins/job/dev-reports-option-editing/)

[<img src="https://devserver3.ustadmobile.com/jenkins/job/dev-customizable-reports-draw-graph-from-data-output-End-To-End-Tests/badge/icon?subject=End-To-End-Tests">](https://devserver3.ustadmobile.com/jenkins/job/dev-customizable-reports-draw-graph-from-data-output-End-To-End-Tests/)

**User story**

As a _teacher or decision maker_ I want _graphs_ so that _I can see progress or lack thereof_.

(If work duration will exceed five days, must be broken down into multiple)

Background info on user story
* info1
* info2

Each series (from ReportEdit) will be return results as a list of 

```
data class ReportResultQueryRow(
    val yAxis: Double,
    val xAxis: String,
    val subgroup: String?
)
```

For bar series (there will be a maximum of one bar chart series per graph): should be as follows:

![Image](https://github.com/user-attachments/assets/fd428037-d4ec-48c6-8b7c-518dd456d4a6)

E.g. for each xAxis value, there should be bar(s) (one if there is no subgrouping, one per subgroup value if subgrouped) . The same subgroup should keep the same color.

For line series:

![Image](https://github.com/user-attachments/assets/40ae26a8-9b87-4f11-a660-326efd05ce8b)

When subgrouped, there is one line per subgroup. If not subgrouped, there is one line
  

**Tasks** 

- [x] @akshattak Complete [wireframe](https://balsamiq.cloud/sagy57t/podvg7r) designs for all screens to be added or modified
- [x] @Anugraha-sutara Create new branch and pull request.
- [x] @poojaustad Create Jenkins job to build automatically on commit and nightly end-to-end build of branch
- [x] @poojaustad Update end-to-end testing scenarios in accordance with user story 
- [x] @poojaustad  Add Cypress and Maestro tests to branch based on testing scenarios/wireframes - expected 13/Feb
- [x] @Anugraha-sutara  Implement code as per design and acceptance criteria: requires successful Jenkins build and end-to-end build. Post video of completion of acceptance criteria on task card. Self check for at least 5-10 minutes.
  - [x] @Anugraha-sutara Display chart on Android/Desktop (jetpack compose) - expected 11/Feb
  - [x] @mikedawson add web chart wrapper (10/Feb)
  - [x] @Anugraha-sutara Display chart on web (13/Feb)
  - [x] @Anugraha-sutara add code that can be used by end-to-end tests to generate usage data. Create a domain use case that generates xAPI statements for a report. This will run only on the server. Add a ktor endpoint that can be used by end-to-end tests to run this.
  - [ ] @mikedawson add label information to run report use case results.
- [ ] @poojaustad check/verify - run any manual sanity checks required
- [ ] @mikedawson check web report runner which appears to be providing empty results now
- [ ] @Anugraha-sutara to add (with design input from Mike) label formatting

Note: this branch should be based on the existing branch for report editing. Change from primary should be merged first into dev-reports-mvvm, then into report editing branch, then into this branch. Pull request should target dev-reports-mvvm.

**Acceptance criteria**

A new branch should be created and [end-to-end testing scenarios](https://github.com/UstadMobile/UstadMobile/tree/primary/test-end-to-end) should be added or modified as required for the user story. Then add links below for all testing scenarios that are newly added or significantly modified:

* [scenario link1](link-to-markdown-for-scenario-in-branch.md) 
* [scenario link2](link-to-markdown-for-scenario-in-branch.md)

**Comment by mikedawson** [comment]
@Anugraha-sutara I added Plotly.kt chart library for the web and demo code in commit 382cf7615f7c5e831d0203738f6d4aec5158f5e2 .

**Comment by Anugraha-sutara** [comment]
![Image](https://github.com/user-attachments/assets/f22f67a4-bf8b-4b94-b33d-c9dc048c284e)
![Image](https://github.com/user-attachments/assets/944fa01f-1c90-4586-816d-89b235f8cc41)
![Image](https://github.com/user-attachments/assets/c726add4-8f27-43c9-982c-3ac7d71f0851)

**Comment by poojaustad** [comment]
Added custom time rage test on cypress & maestro

**Comment by poojaustad** [comment]
Hi @Anugraha-sutara , can you please fix this issue.

![Image](https://github.com/user-attachments/assets/1c28f499-6e44-483d-9f20-74da0224213d)

**Comment by Anugraha-sutara** [comment]
Updated report edit screen as per wireframe

**Comment by mikedawson** [comment]
@Anugraha-sutara to use report SQL generation branch to run report using real data ( task #993 ready)

**Comment by Anugraha-sutara** [comment]
https://github.com/user-attachments/assets/596acaba-6cc3-4def-a9d1-2e130c472249

**Comment by Anugraha-sutara** [comment]
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/84f5ab6f-3807-4dd2-93e3-13218e52c777" />

<img width="140" alt="Image" src= "https://github.com/user-attachments/assets/786f07fe-a3dc-403c-b766-e3874b36011e"/>

**Comment by Anugraha-sutara** [comment]
https://github.com/user-attachments/assets/a33a2619-b492-414d-a26b-c35eac459bed

**Comment by poojaustad** [comment]
Hi @mikedawson, we need to add code that can be used by end-to-end tests to generate usage data for this task

**Comment by Anugraha-sutara** [comment]
Task Status Update:
- **Units not showing** – units are not visible on web –  ✅ Fixed 
- **X-axis selection issue** – If the user selects day/month/year/week on the X-axis, the same option should be disabled in the subgroup. ✅ Fixed 
- **Y-axis selection logic :**
      * If I select YAxisTypes.DURATION, then YAxisTypes.COUNT should be disabled, and vice versa.
      * This check should apply only when more than one series is added.
      * If only one series exists, the user should be allowed to select either. ✅ Fixed 
- Remove series button missing on web – ✅ Fixed
- filter condition selection issue for gender [web]  – ✅ Fixed
- **Gender and class name showing as numbers** – Mike, as we discussed earlier, you mentioned this would be handled in the report result. Right? cc @mikedawson

**Comment by Anugraha-sutara** [comment]
As part of this task, I have also implemented the functionality to edit existing filters. Although this was not originally specified in the task, I felt it would enhance the overall user experience and align well with the existing workflow. cc @mikedawson , @akshattak 

https://github.com/user-attachments/assets/8e9d4588-cd98-4d22-a38a-ed57210c518a

**Comment by Anugraha-sutara** [comment]
Mike,
I just wanted to kindly follow up and clarify two points we had previously discussed, just to make sure we're aligned:

1. Gender and class name appearing as numbers – As per our previous conversation, you had mentioned this would be handled as part of the report result processing on your side.
2. Filter issue in WebApp (https://github.com/UstadMobile/UstadMobile/issues/1088) – In this case, the frontend is collecting and sending the report data to the backend, which then processes it and returns it as a ReportResult. I just wanted to check with you—does this part fall under  task [https://github.com/UstadMobile/UstadMobile/issues/993], or should I look into it further? cc @mikedawson

**Comment by poojaustad** [comment]
Hi  @Anugraha-sutara / @mikedawson , 
In the End-to-end test, I've tried the HTTP call 
url = _/api/generate-xapi-statements/runtest?contentTitle=Content_001&username=stud1_
Manually tested- I am getting data in the report graph
The Cypress test confirms 200 response from the xAPI endpoint, but the graph remains empty in the test run. I've tried adding waits, but I'm still getting empty graphs on Cypress.

**Comment by Anugraha-sutara** [comment]
Hi @poojaustad, I’ve completed the testing to verify that the test server has the correct seeded data, as per your request. Everything looks good — the data has been added correctly from my side. Please let me know if there's anything else you'd like me to check.

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/3def8a48-253a-49ef-b238-7e46f51b64b9" />
<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/d318b944-b02d-4440-8801-62839a92336a" />

**Comment by poojaustad** [comment]
Hi @Anugraha-sutara,
The above-mentioned issue got resolved. On test, it was teacher login, when changed to admin login, the test reports are generated as expected with data. I'll complete this test on Monday morning. Thanks.

**Comment by Anugraha-sutara** [comment]
I’ve updated the list screen UI based on your suggestion and example UI. Could you please review and confirm if it looks good? Let me know if there’s anything else that needs to be added or adjusted. cc @akshattak 

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/a9322eee-80f6-4232-9cf7-751ead94d22f" />

**Comment by mikedawson** [comment]
Reports option should be visible to all users. The concept of showing only "for teachers" is invalid. Users can have different roles in different courses ;e;g a teacher who is also in a training course (where they have a student role).

**Comment by mikedawson** [comment]
@akshattak please update the wireframe to allow the chart to take up the whole width of the card. The chart title can go above the chart. This should be changed to use an adaptive grid (of material design cards ) instead of a fixed list.

**Comment by Anugraha-sutara** [comment]
@akshattak I have updated list screen with grid . please review

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/71ab8392-6b35-4d98-b2be-68844e7b52d9" />


<img src="https://github.com/user-attachments/assets/0436d544-1a2a-4919-9be7-ecf36634125c" width="200" height="400" />

**Comment by mikedawson** [comment]
@Anugraha-sutara the reports icon on the web is actually an error icon. Floating action button should show + Report not + Report_s_

**Comment by Anugraha-sutara** [comment]
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/4f7c0693-ac86-44e9-b796-459dfa01a96f" />

**Comment by mikedawson** [comment]
@akshattak to attach latest prototype designs.

**Comment by Anugraha-sutara** [comment]
Updated Date Formatting Logic

Implemented custom date formatting based on the selected x-axis or subgroup value:

- If Month is selected: format as Month - Year (e.g., June - 2025)
- If Year is selected: format as Year only (e.g., 2025)
- If Week or Day is selected: use the default format dd-MM-yyyy (e.g., 18-06-2025)

Implemented a gender formatting function to convert backend integer values to readable strings:

- 0 → "Male"
- 1 → "Female"

**Comment by Anugraha-sutara** [comment]
<img src="https://github.com/user-attachments/assets/bbdba468-a598-421d-aee9-113af08adc3d" width="200" height="400" />
<img src="https://github.com/user-attachments/assets/b1855582-ac90-45a7-aa0a-95d00f7ffc3d" width="200" height="400" />
<img src="https://github.com/user-attachments/assets/18990655-2663-42e8-9487-269ded9dfd82" width="200" height="400" />
<img src="https://github.com/user-attachments/assets/3ad0b61e-e388-4131-8590-090fefb53e87" width="200" height="400" />

![Image](https://github.com/user-attachments/assets/cf8dc1cb-809d-4181-bee3-2bc73560d8db)

**Comment by mikedawson** [comment]
@Anugraha-sutara please update reports for clarity: e.g. subgrouping by gender when there is only female data doesn't make much sense.
Please add screenshots from web version

@poojaustad please run sanity checks to check formatting logic is as per https://github.com/UstadMobile/UstadMobile/issues/1030#issuecomment-2983756058

**Comment by Anugraha-sutara** [comment]
case1: x axis = day, subgroup = gender
<img src="https://github.com/user-attachments/assets/38aee42f-5cf0-427f-b4bd-5a5575dfc6e0" width="200" height="400">
case1: x axis =month, subgroup =day

<img src="https://github.com/user-attachments/assets/31bec525-de7b-419f-b23f-d9fbb9a1d7bd" width="200" height="400">

case1: x axis =year, subgroup = gender

<img src="https://github.com/user-attachments/assets/43134049-5d58-4c9b-8caa-c988a491f245" width="200" height="400">

case1: x axis =class name , subgroup = gender

<img src="https://github.com/user-attachments/assets/064b7737-53fa-4390-9fa9-9cb551161863" width="200" height="400">

**Comment by mikedawson** [comment]
@Anugraha-sutara next steps
a) Add line charts back to compose
b) Refactor React/web version to be similarly clean / elegant code as per the compose version
c) Likely Monday - add label formatting / handle subgroup edge cases (e.g. multiple series with the same subgroup)

**Comment by poojaustad** [comment]
Hi @akshattak 
On the reports, when the user selects the time range as Last 30 Days, the X-axis currently shows Year, which is not meaningful for such a short range.

<img width="501" height="914" alt="Image" src="https://github.com/user-attachments/assets/74d233a1-e04a-4afb-be6e-81ab8b7f3f9f" />

Suggestion -  Last 30 Days option, the X-axis should ideally display Day, Week. The Year label should only be used when the selected time range spans multiple years.

<img width="502" height="926" alt="Image" src="https://github.com/user-attachments/assets/6a1fd0cb-ecbb-4fd6-84be-05ed6ecd2435" />
